cargo-features = ["codegen-backend"]

[package]
name = "bmstu-os2-matrix-solver"
version = "0.1.0"
edition = "2021"
authors = ["mxxntype <59417007+mxxntype@users.noreply.github.com>"]
description = "none"

[profile.dev]
codegen-backend = "cranelift"

# NOTE: Generated, no unsafe by default.
#
# If you intend on writing unsafe, remove it from here.
[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
correctness = "warn"
suspicious = "warn"
style = "warn"
pedantic = "warn"
nursery = "warn"
complexity = "warn"
perf = "warn"
enum_glob_use = { level = "warn", priority = 1 }
single_match_else = { level = "allow", priority = 1 }
match_bool = { level = "allow", priority = 1 }

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
color-eyre = "0.6.3"
itertools = "0.14.0"
matrixcompare = "0.3.0"
nalgebra = "0.33.2"
nalgebra-sparse = { version = "0.10.0", features = ["compare", "io"] }
plotly = "0.12.1"
rand = "0.9.0"
rayon = "1.10.0"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }

[dev-dependencies]
indoc = "2.0.6"
rstest = "0.25.0"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
